#
debug: true

server:
  port: 8080

spring:
  application:
    name: cron-db-app
  datasource:
    name: myDS
    url: jdbc:h2:file:./data/crondb.h2;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  quartz:
    startup-delay: 3
    auto-startup: true
    wait-for-jobs-to-complete-on-shutdown: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      # never | always
    properties:
      org:
        quartz:
          plugin: false
          scheduler:
            instanceName: QuartzScheduler
            instanceId: AUTO
          jobStore:
            dataSource: myDS
            useProperties: true
            isClustered: false
            class: org.jobs.impl.jdbcjobstore.JobStoreTX
            #class: org.jobs.impl.jdbcjobstore.JobStoreCMT
            #class: org.springframework.scheduling.jobs.LocalDataSourceJobStore
            driverDelegateClass: org.jobs.impl.jdbcjobstore.PostgreSQLDelegate
            #driverDelegateClass: org.jobs.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
          threadPool:
            class: org.jobs.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
            dataSource:
              myDS:
              #provider: org.jobs.impl.jdbcjobstore.H2TableMetaDataJobStoreTXProvider
#            datasource:
#              name: myDS
#              url: jdbc:h2:file:./cron-db/data/crondb.h2;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#              driverClassName: org.h2.Driver
#              username: sa
#              password:
